# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_scaffold_sortable_vho}
  s.version = "3.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Volker Hochstein"]
  s.date = %q{2011-02-01}
  s.description = %q{Sort Tree or List Structures by Drag n Drop}
  s.email = %q{activescaffold@googlegroups.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "active_scaffold_sortable_vho.gemspec",
    "frontends/default/stylesheets/sortable.css",
    "frontends/default/views/_list_with_header.html.erb",
    "frontends/default/views/on_create.js.rjs",
    "frontends/default/views/on_update.js.rjs",
    "frontends/default/views/reorder.js.rjs",
    "init.rb",
    "lib/active_scaffold/actions/sortable.rb",
    "lib/active_scaffold/config/sortable.rb",
    "lib/active_scaffold/helpers/sortable_helpers.rb",
    "lib/active_scaffold_sortable.rb",
    "lib/active_scaffold_sortable/config/core.rb",
    "lib/active_scaffold_sortable/core.rb",
    "lib/active_scaffold_sortable/version.rb",
    "lib/active_scaffold_sortable/view_helpers.rb",
    "lib/active_scaffold_sortable_vho.rb",
    "test/auto_models_controller_test.rb",
    "test/config_test.rb",
    "test/controllers/auto_models_controller.rb",
    "test/controllers/models_controller.rb",
    "test/controllers/sortable_models_controller.rb",
    "test/models/auto_model.rb",
    "test/models/model.rb",
    "test/router_test.rb",
    "test/schema.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/vhochstein/active_scaffold_sortable}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Drag n Drop Sorting for Activescaffold}
  s.test_files = [
    "test/auto_models_controller_test.rb",
    "test/config_test.rb",
    "test/controllers/auto_models_controller.rb",
    "test/controllers/models_controller.rb",
    "test/controllers/sortable_models_controller.rb",
    "test/models/auto_model.rb",
    "test/models/model.rb",
    "test/router_test.rb",
    "test/schema.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<active_scaffold_vho>, ["~> 3.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<active_scaffold_vho>, ["~> 3.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<active_scaffold_vho>, ["~> 3.0"])
  end
end

